# Generated by Django 4.2.5 on 2023-09-28 14:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenityId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('amenityName', models.CharField(max_length=100)),
                ('amenityPicture', models.ImageField(null=True, upload_to='images/amenity/')),
                ('amenityDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrance', models.CharField(choices=[('D', 'daily'), ('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly'), ('O', 'onetime')], default='D')),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventPicture', models.ImageField(null=True, upload_to='images/events/')),
                ('eventData', models.DateTimeField(default=django.utils.timezone.now)),
                ('minTeamSize', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('maxTeamSize', models.IntegerField(default=1)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('penalties', models.IntegerField(default=0)),
                ('ammenityProvider', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('isAdmin', models.JSONField(default=dict)),
                ('bookedEvents', models.ManyToManyField(to='BookingApp.event')),
                ('users', models.ManyToManyField(to='BookingApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('timeRequest', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment', models.ImageField(null=True, upload_to='images/payments/')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.amenity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.event')),
                ('individuals', models.ManyToManyField(to='BookingApp.user')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='userProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.CharField(default='0', max_length=100, primary_key=True, serialize=False)),
                ('timeRequest', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('verified', models.BooleanField(default=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.amenity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.event')),
                ('individuals', models.ManyToManyField(to='BookingApp.user')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.team')),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='userProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
    ]
