# Generated by Django 4.2.5 on 2023-10-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventData',
            new_name='eventDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='individuals',
        ),
        migrations.AlterField(
            model_name='booking',
            name='teamId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.team'),
        ),
        migrations.AddField(
            model_name='booking',
            name='individuals',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
    ]
