# Generated by Django 4.2.5 on 2023-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_rename_eventdata_event_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bookedEvents',
            field=models.ManyToManyField(blank=True, to='BookingApp.event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='isAdmin',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
