# Generated by Django 4.2.5 on 2023-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_alter_team_bookedevents_alter_team_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='individuals',
            field=models.ManyToManyField(blank=True, to='BookingApp.user'),
        ),
    ]
