# Generated by Django 4.2.5 on 2023-10-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_alter_request_individuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenityPicture',
            field=models.ImageField(blank=True, upload_to='images/amenity/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='teamId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.team'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment',
            field=models.ImageField(default=None, null=True, upload_to='images/payments/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='teamId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.team'),
        ),
    ]
