# Generated by Django 4.2.5 on 2023-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0005_amenity_location_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenityPicture',
            field=models.ImageField(upload_to='images/amenity/'),
        ),
    ]
