# Generated by Django 4.2.5 on 2023-10-17 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0010_alter_booking_amenity_alter_booking_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='ammenityDateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
