# Generated by Django 4.2.5 on 2023-10-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0011_amenity_ammenitydateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventPicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
