# Generated by Django 4.2.5 on 2023-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0012_alter_event_eventpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenityPicture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
