# Generated by Django 4.2.5 on 2023-10-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0014_alter_request_amenity_alter_request_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.amenity'),
        ),
        migrations.AlterField(
            model_name='request',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingApp.event'),
        ),
    ]
