# Generated by Django 4.2.5 on 2023-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0018_rename_recurance_amenity_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No Description'),
        ),
    ]
